---
swagger: "2.0"
info:
  description: |
    This is the backend server.
  version: 1.0.0
  title: BEXEventsAndroid
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /BEXEventsAndroid/BEXEventsAndroid/1.0.0
tags:
  - name: events
    description: Everything about each event
    externalDocs:
      description: Find out more
      url: http://swagger.io
schemes:
  - https
  - http
paths:
  /events:
    get:
      tags:
        - events
      summary: Returns all events
      description: All the events are desplayed
      produces:
        - application/json
        - application/xml
      parameters: []
      security:
        - api_key: []
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
        "400":
          description: Invalid status value
  /events/{eventId}:
    get:
      tags:
        - event
      summary: Find event by ID
      description: Returns a single event
      operationId: getEventById
      produces:
        - application/json
        - application/xml
      parameters:
        - name: eventId
          in: path
          description: ID of event to return
          required: true
          type: integer
          format: int64
      security:
        - api_key: []
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/EventById'
        "400":
          description: Invalid ID supplied
        "404":
          description: Event not found
  /event:
    post:
      tags:
        - event
      summary: Create a new event
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: Event
          required: false
          schema:
            $ref: '#/definitions/EventNew'
      security:
        - api_key: []
      responses:
        "200":
          description: successful operation
        "400":
          description: bad request
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  EventById:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: DevTalks2022
      startDateTime:
        type: string
        example: 04-11-2019 14:00
      endDateTime:
        type: string
        example: 04-11-2019 17:00
      duration:
        type: string
        example: 1 week 2 days 3 hours
      location:
        type: string
        example: DB connect
      description:
        type: string
        example: teambuilding event for new DB employees
      organiser:
        $ref: '#/definitions/EventById_organiser'
      attendees:
        type: array
        example:
          - id: 11
            firstName: John
            lastName: Doe
            email: johndoe@gmail.com
          - id: 23
            firstName: Jonas
            lastName: Kahnwald
            email: jonaskahnwald@yahoo.com
          - id: 30
            firstName: Saul
            lastName: Goodman
            email: saulgoodman@db.com
        items:
          $ref: '#/definitions/EventById_attendees'
      isAttendingEvent:
        type: boolean
        example: false
    xml:
      name: EventById
  Event:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      startDateTime:
        type: string
      endDateTime:
        type: string
      duration:
        type: string
      location:
        type: string
    xml:
      name: Event
    example:
      - id: 11
        name: DevTalks2021
        startDateTime: 03-11-2019 14:00
        endDateTime: 03-11-2019 17:00
        duration: 1 week 1 days 2 hours
        location: DB waterfall
      - id: 23
        name: PartyNight
        startDateTime: 04-11-2019 14:00
        endDateTime: 04-11-2019 17:00
        duration: 3 hours
        location: DB ballroom
      - id: 15
        name: Well-being Workshop
        startDateTime: 07-11-2019 14:00
        endDateTime: 08-11-2019 17:00
        duration: 2 days 1 hours
        location: DB connect
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
  EventNew:
    type: object
    properties:
      name:
        type: string
        example: Java Training
      startDateTime:
        type: string
        example: 15-06-22 09:00
      endateTime:
        type: string
        example: 30-06-22 15:00
      duration:
        type: string
        example: 2 weeks 1 day 6 hours
      location:
        type: string
        example: remote
      description:
        type: string
        example: sample text
      organiser:
        $ref: '#/definitions/User'
  EventById_organiser:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
    example: '{"id":11,"firstName":"John","lastName":"Doe","email":"johndoe@gmail.com"}'
  EventById_attendees:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
